### ISSUE TITLE
The annotation "@noproxy" in method Brick\Geo\Geometry::SRID() was never imported. Did you maybe forget to add a "use" statement for this annotation?

### ISSUE THREAD

**Issue by KouloukLeGrand** [brick/geo-doctrine#1]
I was unable to use the library at all since I was unable to get the mapping to work due to this exception:
`The annotation "@noproxy" in method Brick\Geo\Geometry::SRID() was never imported. Did you maybe forget to add a "use" statement for this annotation?`

In fact I was lost due to the lack of documentation and ended up abandoning this promising package.

Is there someone who managed to get this package to work?

**Comment by BenMorel** [comment]
Hi, this is an issue with Doctrine annotations attempting to recognize `@noproxy` as an annotation, when it's really just a marker used internally.

I'm pretty sure this is just a configuration issue, as we're using `geo-doctrine` ourselves at my company with no issue!

**Comment by KouloukLeGrand** [comment]
Hi,

I'm getting jealous rn 😅
Is there an example project I could get to try and find what makes my project mess up?

**Comment by BenMorel** [comment]
What I don't understand is why your project is trying to load annotations from the `Geometry` class, when it should only attempt to read them from entities?

Anyway, you can have a look at [the Annotation docs](https://www.doctrine-project.org/projects/doctrine-annotations/en/1.13/annotations.html#handling-annotations), you can ignore some annotations this way:

```php
AnnotationReader::addGlobalIgnoredName('noproxy');
```

**Comment by KouloukLeGrand** [comment]
I somehow managed to solve this with configuration, mapping and cache clearing.

However I still get issues with SRIDs.
Here is the configuration related to brick/geo-doctrine:
```
doctrine:
    dbal:
        mapping_types:
            point: point
        types:
            point: Brick\Geo\Doctrine\Types\PointType
```
The mapping I set on my entity's attributes:
```
use Brick\Geo\Point;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Embeddable]
class Entity
{
    #[ORM\Column(type: "point")]
    private $point;

    public function getPoint(): ?Point
    {
        return $this->point;
    }

    public function setPoint(Point $point): self
    {
        $this->point = $point;

        return $this;
    }
}
```

I am persisting `(new Entity())->setPoint(Point::xy(0, 0, 4326))` to the database, then trying to get a list of Entities with the EntityRepository:
```
    public function findByClosestTo(string $x, string $y): array
    {
        $point = Point::xy($x, $y, 4326);

        $queryBuilder = $this->createQueryBuilder("entity");
        return $queryBuilder
            ->orderBy($queryBuilder->expr()->asc("Distance(:geometry, entity.point)"))
            ->setParameter(":geometry", (new EWKTWriter())->write($point))
            ->getQuery()
            ->disableResultCache()
            ->getResult();
    }
```

Doing this, I get the following error: `Internal error: 7 ERREUR:  ST_Distance: Operation on mixed SRID geometries (Point, 4326) != (Point, 0) in D:\Users\jejes\PhpstormProjects\deliv4u\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractPostgreSQLDrive
r.php:102`

How can I get over this?

**Comment by BenMorel** [comment]
Hi, please try to add this to your bootstrap script:

```php
Brick\Geo\Doctrine\Types\GeometryType::$srid = 4326;
```

As explained in [the source code](https://github.com/brick/geo-doctrine/blob/42ef0cd3e1a4f92ccf90ed3715641afb6d962381/src/Types/GeometryType.php#L21-L32):

> The default SRID to use for geometries when talking to the database.
>
> This is the SRID that will be used when retrieving geometries from the database,
> as the WKT and WKB formats do not include the SRID information.
>
> Due to current limitations in Doctrine, this will also be used when sending geometries to the database,
> in place of the actual SRID of the geometry.
>
> See: https://github.com/doctrine/orm/issues/4114
>

So basically, due to Doctrine limitations, the SRID of all geometries used as Doctrine entity properties needs to be hardcoded in the Doctrine type.

This should definitely be added to the README. Please let me know is this works for you!

**Comment by BenMorel** [comment]
By the way, some advice:

- you're using PHP 8, so you can use typed properties:
    ```php
    private Point $point;
    ```
- your property is not nullable, so you don't need to make the getter nullable:
    ```php
    public function getPoint(): Point
    ```

**Comment by KouloukLeGrand** [comment]
Thank you for your answer: it worked! I ended up mixing solutions with custom DBAL types for my specific needs.

**Comment by KouloukLeGrand** [comment]
Thank you for your PHP 8 advice too, I didn't know of that either. Really practical!
